artifacts_dir: data

data:
  symbols:
    - KRW-BTC  # Bitcoin - market leader
    - KRW-ETH  # Ethereum - altcoin representative
    - KRW-SOL  # Solana - high-performance L1
  interval_minutes: 60          # 1시간 봉
  window_size: 168              # 7일 (168시간)
  lookahead_candles: 48         # 2일 후 (48시간)
  image_size: 224
  fetch_batch_size: 200
  target_return: 0.05           # 5% 목표
  fee_rate: 0.001
  stride: 12                    # 12시간 간격 샘플링
  moving_averages: [12, 24, 72] # 12h, 1일, 3일 이평선

training:
  batch_size: 32
  learning_rate: 0.0001
  weight_decay: 0.000005
  epochs: 80
  device: cuda
  threshold: 0.55

backtest:
  initial_capital: 1000000
  position_size: 0.1
  stop_loss: -0.03
  take_profit: 0.05             # target_return과 일치

api:
  host: 0.0.0.0
  port: 8000
  reload: true

storage:
  database_path: data/candles.db
